GET http://localhost:3000/postagens/usuario/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzgxNTM1MDY0LCJleHAiOjE3ODE2MjE0NjR9.AJmhzkmzls1dh5Mv9xUw2mzZFBAxG4rFMfmqsec9X-g

